config/routes.rb
Rails.application.routes.draw do

  get 'reviews/create'
  resources :beds do
    resources :bookings, only: %i[create new]
    resources :reviews, only: %i[create]
  end

  resources :bookings, only: %i[index show destroy]

  devise_for :users

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bed.rb
class Bed < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews

  categories = %w[king-size single double water hammock mattress bunk round car]
  validates :category, inclusion: { in: categories }
  validates :title, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :location, presence: true
  validates :description, length: { minimum: 10 }

  has_one_attached :photo

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  include PgSearch::Model
  pg_search_scope :search_by_title_and_location,
    against: [ :title, :location ],
    using: {
      # @@       partial words allowed
      tsearch: { prefix: true }
    }
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :bed
  belongs_to :user

  validates :date, presence: true
  validates :duration, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :bed
end

app/models/user.rb
class User < ApplicationRecord
  has_many :beds
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true

  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :avatar])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :avatar])
  end

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/beds_controller.rb
class BedsController < ApplicationController
  before_action :set_bed, only: %i[show delete edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  def index
    @editor = false
    if params[:search].present?
      @beds = policy_scope(Bed).search_by_title_and_location(params[:search])
    elsif params[:my_beds]
      @beds = policy_scope(Bed).where(user: current_user).order(created_at: :desc)
    elsif params[:category]
      @beds = policy_scope(Bed).where(category: params[:category]).order(created_at: :desc)
    else
      @beds = policy_scope(Bed).where.not(user: current_user).order(created_at: :desc)
    end

    @markers = @beds.geocoded.map do |bed|
      {
        lat: bed.latitude,
        lng: bed.longitude,
        info_window: render_to_string(partial: "info_window", locals: { bed: bed })
      }
    end
  end

  def show
    @booking = Booking.new
    @review = Review.new
  end

  def new
    @bed = Bed.new
    authorize @bed
  end

  def create

    @bed = Bed.new(bed_params)
    @bed.user = current_user
    authorize @bed

    if @bed.save
      redirect_to bed_path(@bed)
    else
      render "new"
    end
  end

  def destroy
    @bed.destroy
    redirect_to beds_path(my_beds: true)
  end

  def edit
  end


  def update
    @bed.update(bed_params)
    redirect_to bed_path(@bed)
  end

  private

  def bed_params
    params.require(:bed).permit(:category, :title, :price, :description, :location, :photo)
  end

  def set_bed
    @bed = Bed.find(params[:id])
    authorize @bed
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show delete] 

  def index
    @bookings = policy_scope(Booking).order(created_at: :desc)
  end

  def new
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.bed = Bed.find(params[:bed_id])
    @booking.total_price = @booking.bed.price * @booking.duration
    authorize @booking
    if @booking.save
      redirect_to bookings_path
    else
      render 'new'
    end
  end

  def show
  end

  def destroy
    @booking.destroy
    redirect_to beds_path
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def booking_params
    params.require(:booking).permit(:date, :duration)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @bed = Bed.find(params[:bed_id])
    @review = Review.new(review_params)
    @review.user = current_user
    @review.bed = @bed
    @booking = Booking.new
    authorize @review
    if @review.save
      redirect_to bed_path(@bed)
    else
      render "beds/show"
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/image_helper.rb
module ImageHelper
  def choose_image(bed)
    if bed.photo.attached?
      cl_image_path bed.photo.key
    else
      asset_path 'new_bed_icon.jpg'
    end
  end
end

app/views/beds/_form.html.erb
  <%= simple_form_for(bed) do |f| %>
    <div class="img-top" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path("hammocky.jpg") %>)">
      <%= f.input :photo, as: :file %>
    </div>
    <div class="form-container">
      <div class="container justify-content-center" >
      <div class="modal-body">
        <%= f.input :title %>
        <%= f.input :location %>
        <%= f.input :price %>
        <%= f.input :description, as: :text %>
        <%= f.input :category, as: :select, collection: %w[king-size single double water hammock mattress bunk round car] %>
      </div>
    </div>


    <div class="w-50 modal-content m-auto bg-#475841">
      <%= f.submit 'Add your Bed', class:'green-btn' %>
  <% end %>
    <button type="button" class="green-btn mt-3" data-dismiss="modal">Back</button>
    </div>
  </div>

app/views/beds/_info_window.html.erb
<h3><%= bed.title %></h3>
<p><%= bed.location %></p>

app/views/beds/edit.html.erb
<%= render "form", bed: @bed %>

app/views/beds/index.html.erb
<div class="d-flex">
  <div class="product-container">
    <div class="background-container">
      <% if @editor %>
        <h2>Your beds </h2>
      <% else %>
        <h2>Find all beds near you </h2>
      <% end %>
      <div class="grid">
        <% @beds.each do |bed| %>
          <%= link_to bed_path(bed) do %>
            <div class="card-product">
                <% if bed.photo.attached? %>
                  <%= cl_image_tag bed.photo.key %>
                <% else%>
                  <%= image_tag 'new_bed_icon.jpg' %>
                <% end %>
                  <div class="card-product-infos">
                      <h2><%= bed.title %></h2>
                      <p><%= bed.description %></p>

                      <p><i class="fas fa-vector-square"></i><%= bed.size %> </p>
                      <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>

                      <h2 class="bed-price"><span><%= bed.price.floor %>$</span></h2>
                  </div>
              </div>
            <% end %>
          <% end %>
      </div>
    </div>
  </div>
  <div id="map"
       style="width: 1140px; height: 80vh;"
       data-markers="<%= @markers.to_json %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>
</div>

app/views/beds/new.html.erb
<%= render "form", bed: @bed %>

app/views/beds/show.html.erb
<div class="container">
  <div class="show-container">
    <div class="img-top" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= choose_image(@bed) %>)">
    </div>
    <div class="info">
      <h2><%= @bed.title %> - <%= @bed.category.capitalize %></h2>
      <p><%= @bed.description %></p>
      <p><%= @bed.price%>€ /h</p>
    </div>
  </div>


  <div class="show-container">
    <% if current_user != @bed.user && params[:review].present? == false %>
      <%= simple_form_for [@bed, @booking] do |f| %>
        <%= f.input :date %>
        <%= f.input :duration %>
        <%= f.submit 'Book bed', class:'green-btn' %>
      <% end %>
    <% elsif current_user == @bed.user %>

      <%= link_to "Update your bed", edit_bed_path, class: "green-btn" %>
      <%= link_to "Delete your bed", bed_path(@bed), class: "green-btn", method: :delete, data: { confirm: 'Are you certain you want to delete this?' } %>
    <% elsif params[:review].present? %>
      <div class="booking-form" style="color: white">
        <%= simple_form_for [@bed, @review] do |f| %>
          <%= f.input :comment %>
          <%= f.submit 'Add', class:'green-btn' %>
        <% end %>
      </div>
    <% end %>
  </div>
  <% unless @bed.reviews.empty? %>
    <div class="review-title">
      <h2>Reviews</h2>
    </div>
    <div class="reviews">
      <% @bed.reviews.each do |review| %>
        <div class="show-container">
          <p> <strong><%= review.user.first_name %></strong> - <%= review.comment %></p>
        </div>
      <% end %>
    </div>
  <% end %>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="booking-container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Booked bed</th>
        <th>Date</th>
        <th>Duration</th>
        <th>Owner</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% unless @bookings.empty? %>
        <% @bookings.each do |booking| %>
          <tr>
            <td><%= booking.bed.title %></td>
            <td><%= booking.date %></td>
            <td><%= booking.duration %></td>
            <td><%= booking.bed.user.first_name %></td>
            <td><%= link_to "Add Review", bed_path(booking.bed, review: true), class: "green-btn" %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <% if @bookings.empty? %>
    <p>Book your first bed!</p>
    <%= link_to 'Explore beds', beds_path, class:"green-btn" %>
  <% end %>
</div>

app/views/bookings/new.html.erb
<h1>Bookings#new</h1>
<p>Find me in app/views/bookings/new.html.erb</p>

app/views/bookings/show.html.erb
<% @booking.date %>
<% @booking.user.first_name%>

<p><% @booking.bed.user.first_name%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_pack_tag 'application' %>
    <title>BlingBlingBling</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@100;300;600&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/shared/_footer.html.erb
<div class="footer">
    <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
        This footer is made with <i class="fas fa-heart"></i> at Le Wagon
    </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon justify-content-between sticky-top">
    <%= link_to root_path do %>
      <div class="navbar-brand">
        <%= image_tag "logo_white.png" %>
      </div>
    <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

        <div class="col">
          <%= simple_form_for :search, url: beds_path, method: :get do |f| %>
          <div class="search-form-control form-group">
            <input class="form-control string required" autocomplete="off" type="text" name="search" id="search_query" value="<%= params[:search] %>" />
            <button name="button" type="submit" class="btn btn-flat">
              <i class="fas fa-search"></i> Search
            </button>
          </div>
        <% end %>
      </div>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "My bookings", bookings_path, class: "nav-link" %>
          </li>
          <% if policy(Bed).create? %>
            <li class="nav-item active">
              <%= link_to "Offer your bed", new_bed_path, class: "nav-link" %>
            </li>
          <% end %>

          
          <% if current_user  %>
            <li class="nav-item active dropdown">
                <% if current_user.avatar.attached? %>
                  <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false, width: 40, height: 40 %>
                <% else %>
                  <%= image_tag "empty_avatar.webp", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false, width: 40, height: 40 %>
                <%end%>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                  <%= link_to "Profile", edit_user_registration_path, class: "dropdown-item" %>
                  <%= link_to "My beds", beds_path(my_beds: true), class: "dropdown-item" %>
                  <%= link_to "Sign out", destroy_user_session_path, class: "dropdown-item", method: :delete %>
                </div>
            </li>
          <% else %>
              <li class="nav-item active">
                <%= link_to "Sign in", new_user_session_path, class: "green-btn" %>
              </li>
          <% end %>
        </ul>
      </div>
  </div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>